DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS ORDER_TABLE;

CREATE TABLE PRODUCT (
	ID INT PRIMARY KEY,
	PRODUCT_DESC VARCHAR(250) NOT NULL,
	PRICE INT NOT NULL,
	STOCK_QTY INT NOT NULL
);


CREATE TABLE ORDER_TABLE (
	ID INT PRIMARY KEY,
	TOTAL_AMOUNT INT,
	PARCEL_FEE INT
);

create sequence hibernate_sequence start 1 increment 1